env:
  es6: true
  browser: true
  commonjs: true

extends: ['airbnb', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'