env:
  es6: true
  browser: true
  commonjs: true

extends: ['airbnb', 'plugin:react/recommended']

rules: 
  react/destructuring-assignment: off
  react/prefer-stateless-function: off
  no-useless-constructor: off
  react/jsx-fragments: off
  import/named: off
  import/extensions: off
  comma-dangle: off

parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'